//primary color: purple #6200EE
export const BaseDarkTheme = {
    name: "Base Dark Theme",
    dark: true,
    version: "0.0.1",
    colors: {
        background: "#121212",
        surface: "#121212",
        primary: "#6200EE",
        "primary-lighten": "#7C4DFF",
        "primary-darken": "#3700B3",
        secondary: "#03DAC6",
        "secondary-lighten": "#5EF1E0",
        "secondary-darken": "#00B5A4",
        success: "#4CAF50",
        "success-lighten": "#66BB6A",
        "success-darken": "#43A047",
        warning: "#FFC107",
        "warning-lighten": "#FFD54F",
        "warning-darken": "#FFA000",
        error: "#FF5252",
        "error-lighten": "#FF6E40",
        "error-darken": "#E53935",
        info: "#2196F3",
        "info-lighten": "#64B5F6",
        "info-darken": "#1976D2",
        "on-background": "#FFFFFF",
        "on-surface": "#FFFFFF",
        "on-primary": "#FFFFFF",
        "on-secondary": "#FFFFFF",
        "on-success": "#FFFFFF",
        "on-warning": "#000000",
        "on-error": "#FFFFFF",
        "on-info": "#FFFFFF",
    },
    variables: {
        'border-color': '#000000',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.60,
        'disabled-opacity': 0.38,
        'idle-opacity': 0.04,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'activated-opacity': 0.12,
        'pressed-opacity': 0.12,
        'dragged-opacity': 0.08,
        'theme-kbd': '#212529',
        'theme-on-kbd': '#FFFFFF',
        'theme-code': '#F5F5F5',
        'theme-on-code': '#000000',
    }
}
